plugins {
	id 'java'
}

repositories {
	maven {
		url = 'https://repo.runelite.net'
	}
	mavenCentral()
}

def runeLiteVersion = 'latest.release'

dependencies {
	compileOnly group: 'net.runelite', name:'client', version: runeLiteVersion

	compileOnly 'org.projectlombok:lombok:1.18.20'
	annotationProcessor 'org.projectlombok:lombok:1.18.20'

	testImplementation 'junit:junit:4.12'
	testImplementation 'org.mockito:mockito-core:3.1.0'
	testImplementation 'com.google.inject.extensions:guice-testlib:4.1.0'
	testImplementation group: 'net.runelite', name:'client', version: runeLiteVersion
	testImplementation group: 'net.runelite', name:'jshell', version: runeLiteVersion
}

group = 'io.hydrox.transmog'
version = '1.3.8'

java {
	sourceCompatibility = JavaVersion.VERSION_11
	targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

// Builds a fat JAR with the plugin inside, then launches RuneLite with it loaded
task run(type: JavaExec, dependsOn: jar) {
	group = 'runelite'
	description = 'Launch RuneLite with this plugin loaded'

	classpath = configurations.testRuntimeClasspath + files(jar.archiveFile)

	mainClass = 'net.runelite.client.RuneLite'

	jvmArgs '-ea',
		"-Drunelite.pluginhub.version=${runeLiteVersion}"
}

// Fat jar so RuneLite can find the plugin class
jar {
	manifest {
		attributes(
			'Implementation-Version': project.version
		)
	}
}
